### ISSUE TITLE
Google without groups seems broken after #2530

### ISSUE THREAD

**Issue by jonkerj** [dexidp/dex#2670]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/dexidp/dex/blob/master/.github/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/dexidp/dex/issues) for an issue that matches the one I want to file, without success.
- [X] I am not looking for support or already pursued the available [support channels](https://github.com/dexidp/dex/issues/new/choose) without success.

### Version

2.34.0

### Storage Type

Kubernetes

### Installation Type

Official Helm chart

### Expected Behavior

I've upgraded dex from v2.33.0 to v2.34.0, and expected the Google connector to keep working.

### Actual Behavior

Dex was crashlooping, complaining about `adminEmail` not being set. After setting `adminEmail`, there was something wrong with default application credentials. 

### Steps To Reproduce

1. Install dex 2.34.0, configure Google according to [the docs](https://dexidp.io/docs/connectors/google/), without `groups`, `serviceAccountFilePath` or `adminEmail`

### Additional Information

It is not really clear to me if this is an actual bug introduced by #2530, or a lack of documentation (which could have been part of #2530). The documentation suggest group/svc account is optional, but these errors suggest otherwise.

In other words: is using Google as a provider without group/svc account still supported?

Downgrading to v2.33.0 still works, so I am guessing it might be a bug.

### Configuration

```yaml
connectors:
- adminEmail: re@dact.ed
  config:
    clientID: $GOOGLE_CLIENT_ID
    clientSecret: $GOOGLE_CLIENT_SECRET
    redirectURI: https://re.dact.ed/callback
  hostedDomains:
  - kippendief.biz
  id: google
  name: Google
  type: google
issuer: https://dex.red.act.ed
staticClients:
- idEnv: CLIENT_OAUTH2_PROXY_ID
  name: OAuth2 Proxy
  redirectURIs:
  - https://foo.bar.red.act.ed/oauth2/callback
  secretEnv: CLIENT_OAUTH2_PROXY_SECRET
- idEnv: CLIENT_GRAFANA_ID
  name: Grafana
  redirectURIs:
  - https://grafana.red.act.ed/login/generic_oauth
  secretEnv: CLIENT_GRAFANA_SECRET
storage:
  config:
    inCluster: true
  type: kubernetes
web:
  http: 0.0.0.0:5556
```

### Logs

```shell
time="2022-09-19T14:09:52Z" level=info msg="Dex Version: v2.34.0-dirty, Go Version: go1.19.1, Go OS/ARCH: linux amd64"
[..]
time="2022-09-19T14:09:52Z" level=info msg="config connector: google"
time="2022-09-19T14:09:52Z" level=info msg="config refresh tokens rotation enabled: true"
failed to initialize server: server: Failed to open connector google: failed to open connector: failed to create connector google: could not create directory service: directory service requires adminEmail
```
```

**Comment by jonkerj** [comment]
I'm testing this with v2.35.1 and it still gives an error:

```
time="2022-10-04T12:49:43Z" level=info msg="Dex Version: v2.35.1-dirty, Go Version: go1.19.1, Go OS/ARCH: linux amd64"
[..]
time="2022-10-04T12:49:43Z" level=info msg="config connector: google"
time="2022-10-04T12:49:43Z" level=info msg="config refresh tokens rotation enabled: true"
time="2022-10-04T12:49:44Z" level=warning msg="the application default credential is used since the service account file path is not used"
failed to initialize server: server: Failed to open connector google: failed to open connector: failed to create connector google: could not create directory service: failed to fetch application default credentials: google: could not find default credentials. See https://developers.google.com/accounts/docs/application-default-credentials for more information.
```

**Comment by sagikazarmark** [comment]
I can't see anything related to admin email here.

How do you configure default creds? `could not find default credentials` suggests the SDK can't find them.

**Comment by jonkerj** [comment]
> How do you configure default creds? `could not find default credentials` suggests the SDK can't find them.

I'm using the config mentioned in the [original post](https://github.com/dexidp/dex/issues/2670#issue-1378030095). I have not done anything with default credentials, just following the [docs](https://dexidp.io/docs/connectors/google/).

**Comment by jonkerj** [comment]
As I can't reopen this issue and it is not fixed for me, should I reopen it?

**Comment by jonkerj** [comment]
After I have skimmed through the commits, I noticed a few commits (cadce3cc3581340559cfd509daf25d0736518477, 9bcce63352c6999831352e8689c69dcaebcdccde, 6a59f08e4edc508162ac282232d78f88c9a1828c) that could be related. So I fired off a build, and it seems current master does not have this bug.

**Comment by jonkerj** [comment]
This issue seems fixed with the release of v2.36.0

**Comment by sagikazarmark** [comment]
It's partially fixed, but it's still broken when groups are required I believe.

**Comment by susguzman** [comment]
The version v2.36.0 worked for me !
